version: "3"

services:
  notebook:
    image: microsoft/cntk:2.1-cpu-python3.5
    container_name: cntk-jupyter-notebooks
    volumes:
     - "./work:/cntk/Keras"
    ports:
     - "8888:8888"
    command: bash -c "source /cntk/activate-cntk && jupyter-notebook --no-browser --port=8888 --ip=0.0.0.0 --notebook-dir=/cntk/Keras --allow-root"
    environment:
     - KERAS_BACKEND=cntk
